site_name: Jambones API
nav:
    - Home: index.md
    - API:
        - jambones Call Control JSON: jambones.md
        - REST API: rest.md
    - Data architecture: data.md
    - Authenticating sip clients: register-hook.md
theme: readthedocs
