site_name: jambonz
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - API:
      - jambonz Webhooks: jambonz.md
      - jambonz REST API: rest.md
  - Installation instructions: installing.md  
  - Data architecture: data.md
  - Authenticating sip clients: register-hook.md
  - Tutorials: tutorials.md
