site_name: jambonz
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - API:
      - jambonz Call Control JSON: jambonz.md
      - REST API: rest.md
  - Data architecture: data.md
  - Authenticating sip clients: register-hook.md
  - Tutorials: tutorials.md