site_name: jambonz API
nav:
    - Home: index.md
    - API:
        - jambones Call Control JSON: jambonz.md
        - REST API: rest.md
    - Data architecture: data.md
    - Authenticating sip clients: register-hook.md
theme: readthedocs
